name: Python Workflow Demo

# on:
#  schedule:
#    - cron: "0/10 * * * *"

on: 
  push:
    branches:
      - main
    paths:
      - "hello.java" # Only Hello.java file
#      - "**.java" # Any Java File
#      - "!index.html" #Except this file, any other file changes, trigger the job

jobs:
  Execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: path
        run: pwd
      - name: list
        run: ls ${GITHUB_WORKSPACE}
      - name: Build Java File
        run: javac /home/runner/work/devsecops-cgi/devsecops-cgi/hello.java
      - name: Run Java File
        run: java HelloWorld
