name: Python Workflow Demo

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: ['3.5', '3.6', '3.7.4', '3.8']
    steps:
      - name: Building the Code
        run: echo "Building the Code"
      - name: Wait for the Code Building
        run: sleep 30

  Execute:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Run Python File
        with:
          python-version: ${{ matrix.python-version }}
      - run: python hello.py
